export type ErrorCode =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'VALIDATION_ERROR'
  | 'INSUFFICIENT_FUNDS'
  | 'ACCOUNT_INACTIVE'
  | 'RATE_LIMITED'
  | 'INTERNAL_ERROR';
